### ISSUE TITLE
DualSense support

### ISSUE THREAD

**Issue by loveisfoss** [epigramx/ds4drv-cemuhook#8]
Hey! I 've just tried ds4drv with a DualSense controller and it does not seem to be working.

Through USB, I get something like this in the terminal, it is getting repeated the whole time. The mouse goes kind of crazy. Yuzu says that it successfully receives data from the UDP server, but it is not usable anyway.

```
python3 -m ds4drv --hidraw --udp --trackpad-mouse
...
[info][controller 1] Connected to USB Controller (00:00:00:00:00:00 hidraw4)
[info][hidraw] Scanning for devices
[info][controller 1] Battery: 37%
[udp] Client 127.0.0.1:47465 disconnected from 0
[info][controller 1] USB: Connected
[info][controller 1] Battery: 9%
[info][controller 1] Audio: Headphones
[info][controller 1] Battery: Fully charged
[info][controller 1] Audio: Mic
[info][controller 1] USB: Disconnected
[info][controller 1] Battery: Fully charged
[info][controller 1] Audio: Speaker
[udp] Client 127.0.0.1:47465 disconnected from 0
[info][controller 1] USB: Connected
[info][controller 1] Battery: 90%
[info][controller 1] Audio: Headphones
[info][controller 1] USB: Disconnected
[info][controller 1] Battery: Fully charged
[info][controller 1] Audio: Headset
[info][controller 1] Disconnected
[info][controller 1] Connected to USB Controller (00:00:00:00:00:00 hidraw5)
[udp] Client 127.0.0.1:47465 disconnected from 0
[info][hidraw] Scanning for devices
[info][controller 1] Battery: 50%
[udp] Client 127.0.0.1:33903 disconnected from 0
[info][controller 1] USB: Connected
[info][controller 1] Battery: 18%
[info][controller 1] Audio: Mic
[udp] Client 127.0.0.1:59444 disconnected from 0
[info][controller 1] USB: Disconnected
[info][controller 1] Battery: 0%
[info][controller 1] Audio: Speaker
[info][controller 1] Battery: Fully charged
[info][controller 1] Audio: Headphones
[udp] Client 127.0.0.1:33903 disconnected from 0
[info][controller 1] USB: Connected
[info][controller 1] Battery: Fully charged
[info][controller 1] Audio: Mic
[info][controller 1] USB: Disconnected
[info][controller 1] Battery: Fully charged
[info][controller 1] Audio: Speaker
[info][controller 1] USB: Connected
[info][controller 1] Battery: 63%
[info][controller 1] Audio: Headphones
[info][controller 1] USB: Disconnected
[info][controller 1] Battery: 62%
[info][controller 1] Audio: Headset
[udp] Client 127.0.0.1:55031 disconnected from 0
[info][controller 1] USB: Connected
[info][controller 1] Battery: 18%
[info][controller 1] Audio: Speaker
[info][controller 1] USB: Disconnected
[info][controller 1] Battery: 0%
[info][controller 1] Audio: Mic
[info][controller 1] Disconnected
```

Throught BT, I get the following.

```
python3 -m ds4drv --hidraw --udp --trackpad-mouse
[info][controller 1] Created devices /dev/input/js1 (joystick) /dev/input/event25 (evdev) 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/__main__.py", line 237, in <module>
    main()
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/__main__.py", line 197, in main
    for device in backend.devices:
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/backends/hidraw.py", line 172, in devices
    yield cls(name=device_name,
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/backends/hidraw.py", line 34, in __init__
    super(HidrawDS4Device, self).__init__(name, addr, type)
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/device.py", line 84, in __init__
    self.set_operational()
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/backends/hidraw.py", line 87, in set_operational
    self.read_feature_report(0x02, 37)
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/backends/hidraw.py", line 63, in read_feature_report
    return fcntl.ioctl(self.fd, op, bytes(buf))
OSError: [Errno 5] Input/output error
^C[info][controller 1] Cleaning up...
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
  File "/home/pol/.local/lib/python3.9/site-packages/ds4drv/__main__.py", line 162, in __call__
    sys.exit(0)
SystemExit: 0
```

**Comment by imsl0wer** [comment]
Same thing happens to me
